### ISSUE TITLE
Escape sequence in package,json

### ISSUE THREAD

**Issue by nihilor** [gemstonejs/gemstone-tool-generator#1]
The generator for a gemstone-meta-project creates an invalid `package.json`. The path literals in the lines 18 and 19 contain an escape sequence, `\e`, that results in an error thrown by `npm install`.

![image](https://user-images.githubusercontent.com/12661131/34287936-a55ac8a4-e6ea-11e7-8568-a35ff3d4882c.png)

**Comment by rse** [comment]
Ah, I see. A Windows issue because of the backslash in paths under Windows. I'll try to fix it. Thanks for the hint.

**Comment by rse** [comment]
OK, this should be now fixed. Please try again with the latest version. Thanks.
